### ISSUE TITLE
Eliminate divide, square root.

### ISSUE THREAD

**Issue by billbudge** [WebAssembly/simd#13]
These would have to be lowered to a series of scalar vdiv and vsqrt instructions on ARMv7.

vdiv takes 15 issue cycles, vsqrt takes 14 issue cycles for 32 bit floats, so about 60 cycles total.

It's better to steer users to the reciprocal and reciprocal square root instructions, and refinement techniques. That doesn't give the exact same result, but SIMD is a performance feature.

**Comment by sunfishcode** [comment]
There are ways that divide and square root can be valuable in a portable API even if they aren't fast on ARMv7.
 - Many potential SIMD users will be porting code from other platforms, or using other portable SIMD APIs. If WebAssembly lacks basic features provided by other popular platforms and APIs, it'll be more difficult to get many application developers to support it. And even when SIMD divide and sqrt aren't faster than scalar, SIMD might still be worthwhile for other parts of the code.
 - Some applications aren't going to run fast on ARMv7 or other devices, but may still be valuable to have on the Web. Of course, we should strive for portability. And, we should be particularly wary of biases. However, if we insist that all compute-heavy applications on the Web must run with acceptable performance on all devices, we'll loose out on applications which need more power than a typical ARMv7 device has anyway.

I also think it's useful to publish documentation explaining to programmers how to use the portable SIMD API to achieve the best portable performance, including things like divide and sqrt being slow, which shuffle patterns to prefer, and so on, and encouraging programmers to utilize approximation techniques where appropriate.

**Comment by billbudge** [comment]
At least in V8, these opcodes will probably be significantly worse than the scalar equivalent on ARM, since our WASM compiler is not going to lower and reschedule the instructions. The code generator will just emit a sequence of vdiv or vsqrt instructions which stall.

I'm wondering, is this true of other WASM compilers?

**Comment by jfbastien** [comment]
My goal for SIMD is to offer performance in a portable manner. I think we're focusing on implementation instead of actual perf. I'd like us to have benchmarks which care enough about div / sqrt to use the SIMD version, and then we can see if we get perf portably, including with ARMv7.

**Comment by juj** [comment]
I'd recommend either directly exposing `_mm_rcp_*`, `_mm_sqrt_*`, `_mm_rsqrt_*`, `_mm_div_*`, `vrecpeq_*`, `vrecpsq_*`, `vrsqrteq_*` and `vrsqrtsq_*` operations so that applications can control how many Newton steps they will need, or having something like the following to cover an union:
   - reciprocal:
      - `_mm_rcp_*` + Newton step on SSE, `vrecpeq_*+vrecpsq_*` + more Newton on NEON
   - reciprocalApproximate
      - `_mm_rcp_*` on SSE, `vrecpeq_*+vrecpsq_*` + less Newton on NEON      
   - squareRoot
      - `_mm_sqrt_*` on SSE, `vmulq*vrsqrteq_*+vrsqrtsq_*` + more Newton on NEON
   - squareRootApproximate
      - `_mm_rcp_*+_mm_rsqrt_*` on SSE, `vmulq*vrsqrteq_*+vrsqrtsq_*` + less Newton on NEON
   - reciprocalSquareRoot
      - `_mm_rsqrt_*`+Newton on SSE, `vrsqrteq_*+vrsqrtsq_*` + more Newton on NEON
   - reciprocalSquareRootApproximate
      - `_mm_rsqrt_*` on SSE, `vrsqrteq_*+vrsqrtsq_*` + less Newton on NEON
   - divide
     -  `_mm_div_*` on SSE, `vmulq_*+vrecpeq_*+vrecpsq_*` + more Newton on NEON.
   - divideApproximate
     -  `_mm_mul_*+_mm_rcp_*`+ on SSE, `vmulq_*+vrecpeq_*+vrecpsq_*` + less Newton on NEON.

and then establish relative error limits for both. The non-approximate versions would lean towards better precision, and the approximate versions toward speed.

**Comment by stoklund** [comment]
I think it is important to distinguish between the exact div/sqrt instructions and the fast approximation instructions. A vectorizing compiler usually won't have the authority to replace exact instructions with approximations, but it will still be able to speed up many loops.

I like the idea of more abstract approximation instructions that can include Newton-Raphson steps depending on the platform. We could have a small number of fixed error limits.

**Comment by stoklund** [comment]
@billbudge, we don't have an ARM implementation of SIMD in Firefox yet, but I expect that we will indeed emit a sequence of vdiv/vsqrt instructions. We don't schedule instructions since even mobile devices tend to have out-of-order CPUs now, so scheduling doesn't have a big effect.

Generating performant floating-point code for an in-order CPU is a whole other matter. As far as I know, no JITs are even trying to do that.

**Comment by jfbastien** [comment]
Given that some at Google expressed that they don't want these instructions, could you make sure to include a poll about them at the upcoming WebAssembly meeting?

**Comment by stoklund** [comment]
Yep. It's closely tied to whether we include the approximation instructions.

**Comment by arunetm** [comment]
Eliminating these from wasm will mean that any existing code/libraries that use the corresponding intrinsics cannot be compiled to wasm without significant loss of performance.   This could deter developers from compiling their preexisting code / frameworks / libraries to wasm which might be re-used by their new applications.  

From a crude GitHub search for _mm_div_ps, _mm_div_ss, _mm_sqrt_ps, _mm_sqrt_ss showed them to be in use in a variety of graphics/simulation libraries.. There seems to be value in having them.


![image](https://cloud.githubusercontent.com/assets/13296674/26651240/e57ea9ae-4600-11e7-939a-71e3cf659bca.png)

**Comment by brycelelbach** [comment]
[This benchmark](https://github.com/brycelelbach/tridiagonal_solve_benchmarks), which is representative of sparse banded heat equation solvers used in finance (black scholes style pricing) and a variety of scientific applications (climate modeling, chemistry, geology, etc), is usually memory bandwidth bound but it is fp divide heavy and is sometimes fp divide bound.

Also, the above search term only captures users of intrinsics and only sse users (no _mm256 or _mm512, etc). Many of us don't write the divide intrinsic explicitly, even if using intrinsics otherwise. Not sure if this is relevant, but a lot of people also use their compilers vectorizer too - e.g. #pragma simd.

As for floating point sqrt... That's even more important.

P.S. vrcp (fast reciprocal) is also important, but more platform specific.

**Comment by dtig** [comment]
Closing this issue as both f32x4.sqrt, f32x4.div are included in the latest version of the proposal.
