### ISSUE TITLE
Exclude f64x2 vector type from initial spec.

### ISSUE THREAD

**Issue by billbudge** [WebAssembly/simd#4]
This type is likely to exhibit the least speedup on platforms that support it (Intel and ARMv8), and may lead to performance hazards on platforms where it must be emulated (ARMv7).

We can revisit this if we can demonstrate a consistent performance benefit for f64x2 vectors on all platforms.

**Comment by jfbastien** [comment]
Right, I think the bar here, as for other things SIMD, it we have to have real-world benchmarks which rely heavily on f64x2, and they must perform close to native in a cross-platform manner.

I don't really care if the first proposal has f64x2 or not, but if it has it then we require more benchmarks to prove SIMD in its entirety is worthwhile.

**Comment by stoklund** [comment]
There's no doubt f64x2 will provide a smaller speedup than the types with more lanes. MIPS and POWER both have native support for f64x2, so as far as I know it is only 32-bit ARM that doesn't. (Not counting very old SSE and MMX).

The peculiar layout of the 32-bit ARM floating point register bank is normally pretty annoying, but in this particular case it also means that emulating f64x2 doesn't require major compiler surgery. You can essentially generate code as if you had the f64x2 instructions, but instead of emitting the non-existent 128-bit instruction:

```asm
vadd.f64 q1, q2, q3
```

you emit two 64-bit instructions instead:

```asm
vadd.f64 d2, d4, d6
vadd.f64 d3, d5, d7
```

Possible performance hazards with this emulation scheme include very old designs like the Cortex-A8 which had separate NEON and VFP units with very long delays to move data between them. An out-of-order core that renames floating point registers 128 bits at a time would have false dependencies in the instruction pairs. I don't know if such designs exist.

I took a look at the [Cortex-A57](http://infocenter.arm.com/help/topic/com.arm.doc.uan0015a/cortex_a57_software_optimisation_guide_external.pdf) which is a more recent design. It renames floating point registers in 64-bit chunks, so there are no partial register write hazards to worry about. From the throughput numbers, it appears that its two SIMD pipelines are 64 bits wide and double-pumped for 128-bit SIMD instructions. This would mean that f64x2 code probably gets very similar performance natively in 64-bit mode and emulated in 32-bit mode.

The double-pumping scheme was also used in early AMD implementations of SSE and early Intel implementations of AVX.

**Comment by billbudge** [comment]
OK, I'm convinced this wouldn't be any worse than the scalar equivalent on ARM.

Closing the issue as resolved.
