### ISSUE TITLE
ETA for GA date?

### ISSUE THREAD

**Issue by unicomp21** [WebAssembly/simd#408]
Given Webassembly/simd is taking so long, perhaps it's not meant to be?  Should we just cancel the whole thing?

**Comment by Maratyszcza** [comment]
WebAssembly SIMD is available in Chrome (under [Origin Trial](https://v8.dev/features/simd#simd-origin-trial), or with `--enable-features=WebAssemblySimd` flag), FireFox Nightly (no experimental flags needed), and several non-browser engines. There are products using it ([TensorFlow.js](https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.html), [Google Meet](https://ai.googleblog.com/2020/10/background-features-in-google-meet.html)). So I don't understand what your complaint is about.

**Comment by unicomp21** [comment]
Why do I have to get a token?  Is there a lack of confidence in the current
implementation?

**Comment by Maratyszcza** [comment]
I do not work on Chrome, but my understanding is that Origin Trial is being used for web standards that are still being developed and promise no backward compatibility with previous versions of their specifications. As the specifications change, developers need to update their web apps, and Origin Trial motivates developers to update their usage of the web standard to the up-to-date specs because the token expires in 6 weeks and needs to be renewed.

**Comment by unicomp21** [comment]
Got it.
